
# NOWARN_CFLAGS += -I/opt/rocm/include -L/opt/rocm/lib
# CFLAGS += -I/opt/rocm/include -L/opt/rocm/lib
# CXXFLAGS += -I/opt/rocm/include -L/opt/rocm/lib

# NOWARN_CFLAGS += -I/opt/cuda/include -L/opt/cuda/lib -L /opt/cuda/targets/x86_64-linux/lib/
# CFLAGS += -I/opt/cuda/include -L/opt/cuda/lib -L /opt/cuda/targets/x86_64-linux/lib/
# CXXFLAGS += -I/opt/cuda/include -L/opt/cuda/lib -L /opt/cuda/targets/x86_64-linux/lib/

LYS_BACKEND = multicore

include ../lib/github.com/abxh/lys/common.mk
