
# NOWARN_CFLAGS += -I/opt/rocm/include -L/opt/rocm/lib
# CFLAGS += -I/opt/rocm/include -L/opt/rocm/lib
# CXXFLAGS += -I/opt/rocm/include -L/opt/rocm/lib

LYS_BACKEND = opencl

include ../lib/github.com/abxh/lys/common.mk
