
# NOWARN_CFLAGS += -I/opt/rocm/include -L/opt/rocm/lib
# CFLAGS += -I/opt/rocm/include -L/opt/rocm/lib
# CXXFLAGS += -I/opt/rocm/include -L/opt/rocm/lib

NOWARN_CFLAGS += -I/opt/cuda/include -L/opt/cuda/lib
CFLAGS += -I/opt/cuda/include -L/opt/cuda/lib
CXXFLAGS += -I/opt/cuda/include -L/opt/cuda/lib

LYS_BACKEND = cuda

include ../lib/github.com/abxh/lys/common.mk
